### ISSUE TITLE
Support for multiple icons for location pins

### ISSUE THREAD

**Issue by scottssutton** [qld-gov-au/page-organisation-map#1]
On the [Science capability directory](http://www.qld.gov.au/dsitia/about-us/business-areas/innovation-science-dev/science-directory/) there are different icons used for different sectors. These icons are displayed on the map itself. 

I'm in the process of putting together a [MAM for roadside stops](http://www.qld.gov.au/transport/contacts/centres/amenities.html) and if I were able to specify a FontAwesome icon for a particular type of centre (rest area, scenic stop, etc) it would make scanning the map easier and more visually appealing.

**Comment by bboyle** [comment]
moved to: https://github.com/qld-gov-au/qgov-mam-angularjs/issues/45
