### ISSUE TITLE
(Feature request) Checkbox for selecting multiple attributes in MAM search

### ISSUE THREAD

**Issue by scottssutton** [qld-gov-au/page-organisation-map#2]
In the MAM search it's possible to use dropdown menus to filter the displayed search results. 

I'm building a [roadside stops map](http://www.qld.gov.au/transport/contacts/centres/amenities.html) that allows you to filter on the amenities they have at a location (for example toilets, picnic tables,  camping, etc). 

If possible it would be great to have tickboxes so that people could select multiple amenities, so they could look for places with fireplaces AND camping AND bush walking tracks.

**Comment by bboyle** [comment]
This issue was moved to qld-gov-au/qgov-mam-angularjs#44
