### ISSUE TITLE
(Feature request) MAM locations that aren't a single point

### ISSUE THREAD

**Issue by scottssutton** [qld-gov-au/page-organisation-map#3]
We're going to be using a MAM to migrate our [infrastructure projects](http://www.tmr.qld.gov.au/Projects.aspx) over to QGov. While the location of some projects can be summed up by a single point, we have others where work is being done over a stretch of highway between 2 points, and others where multiple points might be more appropriate to highlight a non-linear region. Would there be a way of representing more than one point as a line or a region, for a single entry in the CSV?

**Comment by bboyle** [comment]
This issue was moved to qld-gov-au/qgov-mam-angularjs#43
