### ISSUE TITLE
(Feature request) include-style display of external text on MAM

### ISSUE THREAD

**Issue by scottssutton** [qld-gov-au/page-organisation-map#4]
We are going to be migrating our [infrastructure projects](http://www.tmr.qld.gov.au/Projects.aspx) to the QGov website using a MAM.

While we can use markdown language for shorter blocks of text, most of the project pages have a lot of text that would make this difficult. [Example](http://www.tmr.qld.gov.au/Projects/Name/M/Mains-Road-and-Kessels-Road-intersection-upgrade.aspx)

I've tried to get around this by using an include that points to an unformatted page that contains the content, such as: 

 

When I embed the include code into a field in the CSV it just [prints out the code itself onto the page](http://www.qld.gov.au/transport/contacts/centres/amenities.html?title=Mitchelton%20Park-Motorist%20rest%20area-3) whether I use {{ColHeading}} or {{md:ColHeading}}. Replacing the opening < with *ampersand_lt_semicolon* [does not make a difference](http://www.qld.gov.au/transport/contacts/centres/amenities.html?title=Ferguson%20Park-Motorist%20rest%20area-2).

While we could just have links to project pages on the franchise within the individual project entries, that would be a lot of overhead in terms of landing pages, nav files, etc, that we'd like to avoid if possible. If there were something that we could embed within a CSV cell that would execute the include code instead of just displaying the code itself (or any other method of calling content if that's not doable/secure), that would make the formatting of these individual project entries a lot easier.

**Comment by bboyle** [comment]
This issue was moved to qld-gov-au/qgov-mam-angularjs#42
